[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ia_oracle"
version = "0.2.0"
description = "Shared library for Forex System"
requires-python = ">=3.12.10"
dependencies = [
    "google-genai",
    "openai",
    "aiofiles",
    "ollama"
]

[project.optional-dependencies]
dev = [
    "python-dotenv", 
    "pytest"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["ia_oracle*"]
exclude = ["tests*", ".venv*"]
