"""Integration test orchestrator for the IA Oracle Session.

This orchestrator reads the mock output generated by globalintel, constructs
OracleReviewRequest objects, feeds them directly into the OracleSession (bypassing MQ),
and writes the results to an output JSON file to verify the Gemini prompts and logic.
"""

import asyncio
import json
import logging
from pathlib import Path
from typing import Any, Dict, List

from forex_shared.env_config_manager import EnvConfigManager
from forex_shared.domain.oracle import OracleReviewRequest

# Ensure environment is loaded and prioritize .env file
from dotenv import load_dotenv
load_dotenv(override=True)
try:
    EnvConfigManager.startup()
except Exception as _e:
    logging.warning("EnvConfigManager.startup() skipped: %s", _e)

from ia_oracle.session import OracleSession
from ia_oracle.store import OracleCache, OracleMongoStore

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = logging.getLogger("TestOracleOrchestrator")


class TestOracleOrchestrator:
    """Offline test harness for the Oracle Pipeline."""

    def __init__(self, input_file: Path, output_file: Path):
        self.input_file = input_file
        self.output_file = output_file
        
        # Core domain logic
        self.session = OracleSession(session_id="test_runner")
        
        # State
        self.raw_data: List[Dict[str, Any]] = []
        self.results: List[Dict[str, Any]] = []

    async def run(self) -> None:
        logger.info(f"Starting Test Oracle Orchestrator")
        logger.info(f"Input: {self.input_file}")
        logger.info(f"Output: {self.output_file}")
        
        self._load_data()
        if not self.raw_data:
            return

        await self.session.start()

        # Create tasks for all items
        tasks = []
        for i, item in enumerate(self.raw_data):
            # The input file contains the raw Processed Event from GlobalIntel. 
            # We must map this into the OracleReviewRequest contract.
            request = self._build_request_from_mock(item)
            tasks.append(self._process_and_record(request, original_item=item))

        # Execute them concurrently. The OracleSession semaphore will protect against 429s.
        logger.info(f"Dispatching {len(tasks)} tasks to Gemini...")
        await asyncio.gather(*tasks)

        await self.session.stop()
        self._save_results()
        logger.info("Test complete.")

    def _load_data(self) -> None:
        try:
            with open(self.input_file, "r", encoding="utf-8") as f:
                self.raw_data = json.load(f)
            logger.info(f"Loaded {len(self.raw_data)} items from mock data.")
        except Exception as e:
            logger.error(f"Failed to load input file: {e}")

    def _save_results(self) -> None:
        try:
            self.output_file.parent.mkdir(parents=True, exist_ok=True)
            with open(self.output_file, "w", encoding="utf-8") as f:
                json.dump(self.results, f, ensure_ascii=False, indent=2)
            logger.info(f"Saved {len(self.results)} results to output file.")
        except Exception as e:
            logger.error(f"Failed to save output file: {e}")

    async def _process_and_record(self, request: OracleReviewRequest, original_item: Dict[str, Any]) -> None:
        try:
            response = await self.session.process_message(request)
            
            # Record the result alongside the original input for easy comparison
            self.results.append({
                "id": request.trigger_event_id,
                "status": "success",
                "model_used": getattr(getattr(self.session, "_provider", None), "model_name", "unknown"),
                "oracle_request": request.to_dict(),
                "oracle_result": response.to_dict(),
            })
            logger.info(f"Successfully processed {request.trigger_event_id} -> Action: {response.action}")
            
        except Exception as e:
            logger.error(f"Failed to process {request.trigger_event_id}: {e}")
            self.results.append({
                "id": request.trigger_event_id,
                "status": "error",
                "error": str(e),
            })

    def _build_request_from_mock(self, mock_item: Dict[str, Any]) -> OracleReviewRequest:
        """Translates a GlobalIntel ProcessedEvent mock into our new OracleReviewRequest domain object."""
        
        # Depending on how the mock JSON is structured, we extract the needed fields.
        # In the provided sample, the mock already seems to have an "oracle_request" block.
        # We will parse it out if it exists, otherwise we build it from the "enriched_event".
        
        if "oracle_request" in mock_item:
            req_data = mock_item["oracle_request"]
            enriched = req_data.get("enriched_event", {})
            routing = req_data.get("routing", {})
            
            return OracleReviewRequest(
                trigger_event_id=req_data.get("trigger_event_id", enriched.get("id", "unknown")),
                reason=routing.get("routing_reason", "unknown"),
                title=enriched.get("title", ""),
                body=enriched.get("body", ""),
                published_at=enriched.get("published_at", ""),
                source=enriched.get("source", ""),
                domain=enriched.get("domain", ""),
                danger_score_legacy=routing.get("scores_snapshot", {}).get("danger_score_legacy", 0.0),
                impact_category=enriched.get("extra", {}).get("impact_category", "generic"),
                scores=routing.get("scores_snapshot", {}),
                trade_emit_score=routing.get("local_final_decision", {}).get("trade_emit_score", 0.0),
                candidate_directives=routing.get("candidate_directives", []),
                score_breakdown=enriched.get("extra", {}).get("score_breakdown", {}),
            )
            
        # Fallback if the mock is just raw IntelItems
        return OracleReviewRequest(
            trigger_event_id=mock_item.get("id", "unknown"),
            reason="test_harness_fallback",
            title=mock_item.get("title", ""),
            body=mock_item.get("body", ""),
            published_at=mock_item.get("published_at", ""),
            source=mock_item.get("source", ""),
            domain=mock_item.get("domain", ""),
        )

if __name__ == "__main__":
    current_dir = Path(__file__).parent
    input_json = current_dir / "data" / "mock_intel_items_big_process_result.json"
    output_json = current_dir / "data" / "test_oracle_output_results.json"
    
    orchestrator = TestOracleOrchestrator(input_json, output_json)
    asyncio.run(orchestrator.run())
